name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json
      - name: Install client
        run: npm ci
        working-directory: client
      - name: Install server
        run: npm ci
        working-directory: server
      - name: Test client
        run: npm run test
        working-directory: client
      - name: Test server
        run: npm run test
        working-directory: server
